repos:
  # Formatting
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format
        args:
          - --exclude=include/KHR/* 
          - --exclude=include/glad/*
          - --exclude=include/glm/*
          - --exclude=include/GLFW/*
          - --exclude=src/dep/*

  # Linting
  - repo: https://github.com/cpplint/cpplint
    rev: 2.0.0
    hooks:
      - id: cpplint
        args:
          - --filter=-whitespace/parens,-legal/copyright
          - --exclude=include/KHR/* 
          - --exclude=include/glad/*
          - --exclude=include/glm/*
          - --exclude=include/GLFW/*
          - --exclude=src/dep/*
