repos:
  # Formatting
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format 
        exclude: >
          (?x)^(
            include/KHR/.*|
            include/glad/.*|
            include/glm/.*|
            include/GLFW/.*|
            src/dep/.*
          )$

  # Linting
  - repo: https://github.com/cpplint/cpplint
    rev: 2.0.0
    hooks:
      - id: cpplint
        args:
          # NOTE: The whitespace/indent is added because the formatter will indent
          # correctly and the linter typically disagrees with the formatter on this
          - --filter=-whitespace/parens,-legal/copyright, -whitespace/indent, -whitespace/comments, -readability/todo
          - --exclude=include/KHR/* 
          - --exclude=include/glad/*
          - --exclude=include/glm/*
          - --exclude=include/GLFW/*
          - --exclude=src/dep/*
          - --exclude=others/*
