repos:
  # Formatting
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format

  # Linting
  - repo: https://github.com/cpplint/cpplint
    rev: 2.0.0
    hooks:
      - id: cpplint
        args:
          - --filter=-whitespace/parens, -legal/copyright
          - --exclude=include/KHR/*, include/glad/*, include/glm/*, include/GLFW/*, src/dep/*


